frintjs/frint

docs/guides/create-app/Actions.md, src/createApp.js
Signed-off-by: Alex Miranda <alexmirandamoraes@gmail.com>
=> Apply patch from POC repository

CONTRIBUTING.md
=> Docs: Guidelines for Pull Requests

test/createModel.spec.js
- Adds the createModel.spec.js.
- Diffs
- `npm test`
Added the test `createModel.spec.js`
=> Adds the createModel.spec.js

test/Model.spec.js
- Adds the `test/Model.spec.js`
- Diffs
- `npm test`
Added the test `test/Model.spec.js`
=> Adds the Model.spec.js

src/components/mapToProps.js
=> Pass default merge function to mapToProps

docs/api/createComponent.md, src/createComponent.js, test/createComponent.spec.js
Adds getDOMElement() to createComponent.js
Adds a new test on the createComponent.spec.js to test the new method.
- Diffs
Improved the createComponent.spec.js unit test.
=> Adds getDOMElement() to createComponent.js

src/createApp.js
Checks `process.env.NODE_ENV`, and if the value is `production`, it won't load logger.
---
Next: our webpack configs in private repos need to pass `process.env.NODE_ENV` via DefinePlugin. coming soon.
=> Do not load logger in production mode

docs/README.md, docs/faq.md, src/createComponent.js, test/createComponent.spec.js
* added FAQ section
* improvement on createComponent method
=>  FAQ section and improvement on createComponent method

README.md
Adds [node security project](https://nodesecurity.io)'s badge to the `README.md`.
- Diffs
=> Adds node security project's badge to the README.md

src/createApp.js
The leak is taken care of here already: https://github.com/Travix-International/frint/blob/dd30cdfe31b42951e70f065b8b5f16dfaa7ee396/src/createApp.js#L253
=> Remove TODO for leak that is already taken care of

docs/api/mapToProps.md, src/createApp.js, test/components/Region.spec.js, test/components/mapToProps.spec.js, test/createApp.spec.js, test/server/renderToString.spec.js
* `appId` is not really required in `frint` as a framework
* So removed
=> Remove `appId` as a requirement

MAINTAINERS.md
Renamed `CONTRIBUTING.md` to `MAINTAINERS.md` file, since it is targetted towards us maintainers only.
=> Maintainers guide

src/createApp.js, test/createApp.spec.js
Which passed to Component. It's a solution to pass component properties from frint-test
=> Adds support to "render" method of "createApp" for arguments

dist/webpack.config.js, package.json
Upgraded to latest Webpack version, for dist generation: https://webpack.js.org/configuration/
=> Upgrade webpack to v2.2.0

examples/counter/core/webpack.config.js, examples/multiple-widgets/core/webpack.config.js, examples/multiple-widgets/widget-bar/webpack.config.js, examples/multiple-widgets/widget-foo/webpack.config.js
=> Examples: update build configs to be compatible with latest webpack@2.x

docs/api/createModel.md
Documentation for `get` method.
=> Documentation for Model `get` method

site/content/guides/apps.md, site/content/guides/components.md, site/content/guides/higher-order-components.md, site/content/guides/providers.md, site/content/guides/regions.md, site/partials/footer.html, site/partials/guidesSidebar.html
Added guides for understanding:
* App
* Provider
* Component
* Region
=> Guides: Concepts of App, Provider, Component, Region

site/assets/css/site.scss, site/assets/js/site.js, site/content/guides/code-splitting.md, site/content/guides/state-management.md, site/partials/guidesSidebar.html
* Guides:
* State management
* Code splitting
* Fixes for scrolling to anchors in the same page
* http://frint-site.bitballoon.com/guides/state-management/
* http://frint-site.bitballoon.com/guides/code-splitting/
=> Docs: Guides for State Management and Code Splitting

site/partials/assets.html
* Added Google Analytics
* Core Team already granted access (check your emails)
=> Site: analytics

MAINTAINERS.md, Makefile
* Command added for publishing site to GitHub Pages
```
$ make site-publish
```
=> Site: command for publishing site.

site/content/guides/observables.md, site/partials/guidesSidebar.html
* Guide written for getting started with Observables
=> Guides: Observables

package.json, packages/frint-react-server/src/renderToString.spec.js
* Test for server-side rendering with props coming from Observable
=> Test: Server-side rendering with props coming from Observable

.travis.yml, package.json, packages/frint-compat/package.json, packages/frint-model/package.json, packages/frint-react-server/package.json, packages/frint-react/package.json, packages/frint-store/package.json, packages/frint-test-utils/package.json, packages/frint/package.json
Combine coverage reports of multiple packages into one single lcov file, and then send it to coveralls.
=> Coveralls integration for monorepo

packages/frint-model/README.md, packages/frint/webpack.config.js
Add missing `Install` section for `frint-model`
=> Add install section to frint-model docs

packages/frint-preset-travix/package.json
=> Pin package versions in Travix preset

site/assets/css/content.scss
Adjusted selection color (#146)
=> Changed selection color (#146)

LICENSE, package.json
**What:**
Update copyright year in LICENSE file
**Issue:** 
Closes #173
=> Update copyright year in LICENSE file

site/content/docs/migration/v1.md
Guide detailing how to use React directly.
=> Docs: migration guide for components

.alexignore, .alexrc, package.json
Continuing with the temporary fix by @gtzio in #187, upgraded `alex` to latest minor, and also now checking ALL the markdown files we have in the repo.
And yeah, had to manually allow @jackTheRipper in `.alexrc`.
```
$ npm run alex
> frint@ alex /Users/FHeylaal/Work/frint
> alex .
CHANGELOG.md: no issues found
MAINTAINERS.md: no issues found
README.md: no issues found
examples/counter-ts/README.md: no issues found
examples/counter/README.md: no issues found
examples/kitchensink/README.md: no issues found
examples/multiple-apps/README.md: no issues found
packages/frint-compat/README.md: no issues found
packages/frint-model/README.md: no issues found
packages/frint-preset-travix/README.md: no issues found
packages/frint-react-server/README.md: no issues found
packages/frint-react/README.md: …
```
=> Upgrade `alex`, and check all markdown files

packages/frint-compat/src/Region.spec.js, packages/frint-compat/src/createApp.spec.js, packages/frint-compat/src/createComponent.spec.js, packages/frint-compat/src/extendApp.spec.js, packages/frint-compat/src/mapToProps.spec.js, packages/frint-react/src/components/Region.spec.js, packages/frint-react/src/components/observe.spec.js
First noticed in #198 Travis-CI builds.
=> ESLint fixes in tests

package.json, packages/frint-cli/README.md, packages/frint-model/README.md, site/content/docs/packages/frint-cli.md, site/partials/docsSidebar.html
=> Show `frint-cli` docs in site

.alexrc
Added a few more words in the `allow` list. Otherwise latest `minor` release is breaking the builds.
It's a bit disappointing that their minor releases break it for us: https://github.com/wooorm/alex
=> Fixes for `alex`.

packages/frint-react/README.md
=> Minor fix for docs in frint-react

site/content/docs/migration/v2.md, site/partials/docsSidebar.html
* Added migration guide for moving to v2.x from 1.x
=> Migration guide for v2.x

examples/counter-ts/package.json, examples/counter/core/components/Root.js, examples/counter/package.json, examples/kitchensink/app-color/components/Root.js, examples/kitchensink/app-counter/components/Root.js, examples/kitchensink/app-reversed/components/Root.js, examples/kitchensink/app-todos/components/Item.js, examples/kitchensink/app-todos/components/Root.js, examples/kitchensink/core/components/Root.js, examples/kitchensink/package.json, examples/multiple-apps/app-bar/components/Root.js, examples/multiple-apps/app-foo/components/Root.js, examples/multiple-apps/core/components/Root.js, examples/multiple-apps/package.json
* Upgraded all examples to FrintJS v2
* All React warnings fixed in examples
=> Upgrade all examples  to FrintJS v2.x

packages/frint-compat/src/createService.js, packages/frint/src/App.spec.js
* Fixes lint issues detecteqd with the newest version of `eslint-config-travix`/`eslint-config-airbnb`
- Diffs
=> Fixes lint issues detected with the newest version of eslint-config-travix

site/content/docs/packages/frint-router-react.md, site/content/docs/packages/frint-router.md, site/content/guides/routing.md, site/partials/docsSidebar.html, site/partials/guidesSidebar.html
Haven't covered following topics yet:
- Route placeholders (/route/:whatever)
- Async loading with code splitting
=> Guide for routing

packages/frint-router-react/src/Link.js, packages/frint-router-react/src/Link.spec.js
Addressing @markvincze's [review comment](https://github.com/Travix-International/frint/pull/244#discussion_r130300556)
=> frint-router-react: Link: avoid pushing url if it's current one

examples/router/vendors/index.js, packages/frint-router/README.md, packages/frint-router/src/makeRouterService.js, packages/frint-router/src/makeRouterService.spec.js
Implemented caching for route matches.
=> Router: caching

site/assets/css/global.scss, site/assets/css/header.scss, site/content/README.md, site/content/about/README.md, site/layouts/home.html, site/partials/footer.html
* Homepage header updated
* Button given more prominence
The homepage will most likely follow more changes, to deliver a better message about how this project can benefit you as a developer.
Related to #250
=> Homepage: header updated

site/layouts/repl.html
=> Site: fix REPL by loading `prop-types`.

examples/kitchensink/.gitignore, examples/kitchensink/app-color/app/index.js, examples/kitchensink/app-color/components/Root.js, examples/kitchensink/app-color/constants/index.js, examples/kitchensink/app-color/epics/color.js, examples/kitchensink/app-color/epics/index.js, examples/kitchensink/app-counter/components/Root.js, packages/frint-store/src/ActionsObservable.js, packages/frint-store/src/Store.js, packages/frint-store/src/combineEpics.spec.js, packages/frint-store/src/createStore.spec.js
- New unit tests for combineEpics implementation
- Added epic async functionality in kitchensink example application
=> frint-store: example and unit tests

examples/kitchensink/app-color/app/index.js, examples/kitchensink/app-color/components/Root.js, examples/kitchensink/app-color/constants/index.js, examples/kitchensink/app-color/epics/color.js, examples/kitchensink/app-color/epics/index.js, examples/kitchensink/app-counter/components/Root.js, packages/frint-store/README.md, packages/frint-store/src/ActionsObservable.js, packages/frint-store/src/Store.js, packages/frint-store/src/combineEpics.js, packages/frint-store/src/combineEpics.spec.js, packages/frint-store/src/createStore.spec.js, packages/frint-store/src/index.js
* Implemented #242 (Epics in `frint-store`)
=> frint-store: Epics

README.md, site/content/docs/migration/v3.md, site/partials/docsSidebar.html
Migration guide to v3.
(May get extended further)
=> Docs: Migration guide to v3

examples/counter-ts/package.json, examples/counter/package.json, examples/counter/vendors/vendor.js, examples/counter/webpack.config.js, examples/kitchensink/package.json, examples/kitchensink/vendors/vendor.js, examples/kitchensink/webpack.config.js, examples/multiple-apps/package.json, examples/multiple-apps/vendors/vendor.js, examples/multiple-apps/webpack.config.js, examples/router/package.json, examples/router/vendors/index.js, examples/router/webpack.config.js
All examples in the repo have been upgraded to FrintJS v3.
=> Examples: Upgraded to FrintJS v3

Makefile, site/assets/css/content.scss, site/layouts/repl.html
=> REPL: use Codesandbox.

site/content/docs/migration/v3.md, site/content/docs/migration/v4.md, site/partials/docsSidebar.html
Migration guide for upcoming v4 release.
Continuation from #350.
=> Migration guide for v4

packages/frint-react/README.md, packages/frint-react/src/components/Region.js, packages/frint-react/src/components/Region.spec.js
I've followed the issue #337  and I have added the `className` to `Region` component.
Closes #337
=> frint-react: className prop in Region component

README.md
* Updates NSP Badge on README.md
Why? In order to solve the issue with NSP (Node Security Platform) I had to re-add the project, since it has changed organization.
- Diffs.
=> Updates NSP badge on README.md

README.md
Points to: https://gitter.im/frintjs/frint
=> Gitter URL updated

CONTRIBUTING.md, MAINTAINERS.md
This PR adds contribution guide for anyone willing to participate in the development of FrintJS.
=> Contribution guide

packages/frint-react/README.md, packages/frint-react/src/components/Region.js, packages/frint-react/src/components/Region.spec.js
=> Region component added render prop support
