frintjs/frint

- src/components/Region.js
Issue:
Region component was rendered twice because of `setState` being called during `componentDidMount`
Fix
Change `componentDidMount` to `componentWillMount`.
> Fix rendering twice issue

- src/components/Region.js
Changes made:
1. Added callback after `setState` to make sure we have the list of registered widgets ready before iterating over list
1. Refactored direct state change prior to call to `this.setState({ listForRendering })`.  Now creates new `listForRendering` and call `setState`.
1. Implemented `shouldComponentUpdate` to make sure that after all dependencies are loaded, which causes a change to `this.state.listForRendering`, only then the component is re-rendered
> Optimise region to only re-render when listForRendering changes

- test/createComponent.spec.js
- test/createFactory.spec.js
- Adds the usage of `sinon.sandbox` to create and restore stubs/spies, to not pollute other tests.
- Adds a new test for the `createFactory()`, only testing the result expectations.
- Diffs
- Run `npm test`
- Adds the test `test/createFactory.spec.js`.
> Adds the createFactory spec

- test/createComponent.spec.js
- Changes the `test/createComponent.spec.js` to make the code's behavior more _readable_ (thanks @alexmiranda).
- Diffs
Updated the `test/createComponent.spec.js`.
> Improves the createComponent.spec.js

- test/components/Provider.spec.js
- test/mocha.opts
- Changes the `test/mocha.opts` to have the `--recursive` flag which enables mocha to search through sub-folders for specs.
- Adds the new spec `test/components/Provider.spec.js`
- Diffs
- `npm test`
Added a new test `test/components/Provider.spec.js`
> Adds the Provider's spec

- test/render.spec.js
- test/setup.js
- Changes the `test/setup.js` to add another DOM element ( `<div id="root"></div>` to be used for rendering components (avoiding to render in the `body` element and getting a warning).
- Adds the `test/render.spec.js`
- Diffs
- `npm test`
- Adds spec `test/render.spec.js`
> Adds the render spec

- test/createApp.spec.js
- test/createComponent.spec.js
- test/createFactory.spec.js
- test/createService.spec.js
- Converts `function ()` to `() =>` in all specs that were using them.
- Adds a test in the `createFactory.spec.js` to test if the constructor throws an error when no app instance is provided.
- Adds the `createService.spec.js`.
- Diffs.
- `npm test`
All tests that were using anonymous functions were converted to arrow functions.
Added the test `test/createService.spec.js`
> Adds createService spec

- docs/README.md
- docs/api/Component.md
- docs/api/PropTypes.md
- index.js
- src/PropTypes.js
- test/PropTypes.spec.js
Now you can import and use PropTypes as follows:
```js
import { createComponent, PropTypes } from 'frint';
const MyComponent = createComponent({
propTypes: {
name: PropTypes.string.isRequired
},
render() {
return (
<p>Name is {this.props.name}</p>
);
}
});
```
Yes
> Expose PropTypes

- .gitignore
- src/components/mapToProps.js
With this PR you will be able to inject models directly into component, such as:
```js
const MyComponent = createComponent({
render() {
// expects model to be provided via props
const { model } = this.props;
// use model
const something = model.getSomething();
}
});
export default mapToProps({
models: {
model: 'model'
}
})(MyComponent);
```
> Support for injecting models

- index.js
We need this so that Babel can be ignored while bundling third-party vendors.
Would make things faster for us.
> Make root index.js es5 compatible

- src/components/Region.js
- test/components/Region.spec.js
When two different apps with the same widget name tried to render in the same Region, only one was rendered.
E.g.
myFirstApp - helloWorldWidget
mySecondApp - helloWorldWidget
This PR fixes that.
(Proof)
- Diffs
- With the current master, try to create 2 widgets with the same name and different appNames and target the same region. Only 1 will render. The other one will be assumed as rendered (due to [this previous check](https://github.com/Travix-International/frint/compare/fix-region-to-differentiate-apps-with-same-name?expand=1#diff-fbd171f24f3d6b7eb868c635ff42166eL72)).
Tests were added for `components/Region.js`.
> Fixes Region to differentiate widgets with the same name but different appNames

- src/components/mapToProps.js
- src/createApp.js
- test/components/mapToProps.spec.js
- test/setup.js
To reproduce: 
* Create Widget `A` and `B`
* `B` wants to read state of `A`
* When `B`'s container component is rendered, it doesn't have the state from `A` **initially**
* Only after a new action has been fired in `A`'s store, `B` gets the state right way
* Instead of only updating the state from inside the subscription, we are now passing the state initially too, to make sure it is available to Container components at all times.
---
* A new `resetDOM` function in tests to clear globals in mocha
* Unit tests for `mapToProps` function
* Coverage increased from 64% to **83%**
> Fix: for passing initial shared state across Widgets

- CHANGELOG.md
- CONTRIBUTING.md
* `CHANGELOG.md` file is automatically generated from GitHub data (not just Git alone)
* Docs updated in `CONTRIBUTING.md` so that maintainers can generate the changelog themselves too
> Changelogs

- docs/api/createService.md
- src/createService.js
- test/createFactory.spec.js
- test/createService.spec.js
* In Services and Factories, we check if an `initialize` method is available or not
* If available, we execute that during the class construction phase without any arguments
```js
const MyFactory = createFactory({
initialize() {
// doSomething()
}
});
```
* Now when executing the `initialize()` method, we are passing the constructor options as arguments too
```js
const MyFactory = createFactory({
initialize(options) {
// `options.app` === app
}
});
```
It is very handy while unit testing, and make assertions based on what options were passed to the Factory (or Service) during construction easier to tackle. I ran into it while writing tests for a new `Logger` Factory (internally uses `travix-logger` package).
> Trigger `initialize()` method in Service and Factory with constructor options

- README.md
- test/components/mapToProps.spec.js
- test/createApp.spec.js
- test/middlewares/appendAction.js
* Added tests for mapping Model to props via `mapToProps`
* Added tests for `createApp`
* Added tests for internal `appendAction` middleware
* Add badge to Coveralls in README
> Tests: for `mapToProps`, `createApp`, and middleware

- docs/api/App.md
- src/createApp.js
- test/createApp.spec.js
- Introduced new `setRegions` method, accepting multiple Region names
- Existing `setRegion` still exists, and calls `setRegions` internally.
Note: not a breaking change. done mainly to be more in line with the `app.manifest` file, which stores the region names as an array under `targetContainers` key.
> App: new `setRegions` method

- docs/README.md
- docs/api/server/README.md
- docs/api/server/renderToString.md
- src/server/index.js
- src/server/renderToString.js
- test/server/renderToString.spec.js
New `renderToString` function has been introduced, which is available only in the server-side.
Accepts an `app` instance, and renders it to String.
**Note**: No breaking changes.
Docs and tests are in the diff.
```js
import { renderToString } from 'frint/lib/server';
import MyApp from '../app'; // your custom frint App class
const app = new MyApp();
const html = renderToString(app);
```
> Server-side rendering

- package.json
- src/createApp.js
- src/middlewares/async.js
- test/components/mapToProps.spec.js
- test/middlewares/async.js
* Introduced new `async` middleware which is used internally instead of `redux-thunk`
Dependencies removed:
* `redux-thunk`: replaced by new middleware in this PR
* `react-redux`: which was already made redundant by previous PRs
**Note**: not a breaking change.
Tested both at `mapToProps` level, and also at unit level for the new middleware.
> Middleware for asynchronous actions

- package.json
* Removes `prepublish` hook from `package.json` file
* The action already exists in `Makefile`
> Remove redundant `prepublish` hook, already taken care of by `Makefile`.

- .gitignore
- package.json
* Adds common patterns for 'macOS', 'OSX', 'VisualStudioCode', 'SublimeText' and 'WebStorm' to the `.gitignore`.
* Adds a section _greenkeeper_ to the `package.json` in order to specify packages to ignore (we don't want to upgrade `react` and `react-dom` for now)
- Diffs
N/A
> Adds greenkeeper ignore and updates .gitignore

- package.json
* Changes `alex:code` script on `package.json` to pass a specific glob to `alex` instead of doing a `find`. `alex` already ignores `node_modules` so no need to ignore them either.
- Diffs
N/A
> Uses alexjs's ability to receive globs in order to parse other extensions

- src/createApp.js
- test/createApp.spec.js
* We depend on `name` for sharing state between Widgets
* Since it is so important, it has been made a required key when creating App class
> Make `name` a required option in App

- .gitignore
- Makefile
- dist/webpack.config.js
- package.json
When `frint` is published to `npm` next time, it would generate and upload the dist files too, and that would make it available via CDN:
Example URL: https://unpkg.com/frint@0.10.1/dist/frint.min.js
```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.14.8/react.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/0.14.8/react-dom.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/rxjs/5.0.0-rc.5/Rx.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.2/lodash.min.js"></script>
<script src="https://unpkg.com/frint@0.10.1/dist/frint.min.js"></script>
<script>
// frint is now available as `window.Frint`
</script>
```
> Generate dist when publishing to npm

- src/createApp.js
This check is needed to use `frint` in server-side, without involving any `jsdom` magic in globals.
> Check if `window` exists before setting Root app

- src/components/Region.js
This is again needed for server side rendering, in non-testing environments.
> Check if `window` exists in Region

- .babelrc
- .eslintrc
- SUMMARY.md
- docs/api/Component.md
- docs/api/Region.md
- docs/api/createComponent.md
- docs/api/h.md
- docs/api/mapToProps.md
- docs/guides/create-app/Component.md
- docs/guides/create-app/Transpiler.md
- src/combineReducers.js
- src/components/Region.js
- src/components/mapToProps.js
- src/createApp.js
- src/h.js
- src/index.js
- src/render.js
- src/server/renderToString.js
- test/Model.spec.js
- test/PropTypes.spec.js
- test/components/Provider.spec.js
- test/components/Region.spec.js
- test/components/mapToProps.spec.js
- test/createComponent.spec.js
- test/createFactory.spec.js
- test/createModel.spec.js
- test/createService.spec.js
- test/render.spec.js
- test/server/renderToString.spec.js
We are still dependent on JSX being transpiled into code like `React.createElement(...)`, which makes it a requirement for us to expose `React` globally.
In the browser we are not facing any issues, because React is available globally already as `window.React`.
But in the server-side, it's a problem unless you set `global.React = require('react')`.
Instead of depending on React globally, we are now exposing an `h` function, which we can import wherever we use JSX.
And it comes from `frint`.
`h` is the replacement of direct usage of `React.createElement`.
The `h` function needs to exist in the scope, wherever we use JSX.
```js
import { createComponent, h } from 'frint';
export default createComponent({
render() {
return (
<p>Hello World</p>
);
}
});
```
And it gets transpiled to:
```js …
```
> Hyperscript for JSX

- examples/config.js
- examples/counter/README.md
- examples/counter/build/index.html
- examples/counter/core/app/index.js
- examples/counter/core/components/Root.js
- examples/counter/core/index.js
- examples/counter/core/reducers/index.js
- examples/multiple-widgets/README.md
- examples/multiple-widgets/build/index.html
- examples/multiple-widgets/core/app/index.js
- examples/multiple-widgets/core/components/Root.js
- examples/multiple-widgets/core/index.js
- examples/multiple-widgets/widget-bar/app/index.js
- examples/multiple-widgets/widget-bar/components/Root.js
- examples/multiple-widgets/widget-bar/reducers/index.js
- examples/multiple-widgets/widget-foo/app/index.js
- examples/multiple-widgets/widget-foo/components/Root.js
- examples/multiple-widgets/widget-foo/reducers/index.js
In the examples, use CDN url for loading `frint` in the browser, resulting in smaller bundle sizes for Core apps and Widgets (`<= 8kB unminified` each).
The CDN url is: https://unpkg.com/frint@0.x/dist/frint.min.js
**Hint**: Look into `index.html` files in the diff.
> Examples: use CDN url for `frint`

- examples/counter/Makefile
- package.json
- src/createApp.js
- src/middlewares/logger.js
- test/middlewares/logger.spec.js
* Custom logger middleware
* `redux-logger` package removed
* With this PR, all direct dependents of `redux` has been removed
* Now leaves us with the possibility of directly using `rxjs` for Stores
**Note**: NOT a breaking change. Behaviour is still same like before.
> Logger middleware

- CNAME
- package.json
Once the `CNAME` file gets deployed to GitHub Pages, we can request for a `frint.js.org` domain name via https://dns.js.org/
> CNAME for frint.js.org

- src/createStore.js
Deprecation warning removed, since `getState()` is still heavily expected to be used in async actions.
Current `master` is not released yet, so the previous warning never made it into a release.
> Undeprecate `Store.getState()`.

- docs/api/createModel.md
- src/createModel.js
- test/createModel.spec.js
Like services and factories, a new `initialize()` lifecycle method has been added.
```js
// ./models/MyModelName.js
import { createModel } from 'frint';
export default createModel({
initialize(attributes = {}) {
// `attributes` contains all constructor options
}
});
```
> Models: `initialize` lifecycle method.

- src/Model.js
- test/Model.spec.js
There are few improvements are proposed in the PR:
1. Always create an object for attributes field when creating a Model. It will prevent situation when the single value or undefined can be passed to it.
2. Introduce the get method as a common approach to retrieve a value from attributes field. The get method support complex keys and actually uses lodash get.
> Improve model functionality

- package.json
- src/compat/Region.spec.js
- src/compat/createApp.spec.js
- src/compat/mapToProps.spec.js
- src/react/components/Region.spec.js
- src/react/components/observe.spec.js
- src/react/createComponent.spec.js
- src/react/render.spec.js
- test/mocha.opts
- test/setup.js
* Remove `jsdom-global` package
* Setting up DOM objects like before, in `test/setup.js` via `resetDOM`
* Full `npm test` was running fine, but
* Individual plugin tests when ran separately, like `react`, was failing
* Don't wanna wait for jsdom-global gotchas and move on
1. Linting
1. Full test suite
1. React tests
1. Compat tests
> Remove jsdom-global package.

- packages/frint-react/src/components/Region.js
- packages/frint-react/src/components/Region.spec.js
- packages/frint/README.md
- packages/frint/package.json
- packages/frint/src/App.js
- packages/frint/src/App.spec.js
* When multi-instance Widgets are unmounted:
* The instances are destroyed
* And the root app also clears them from internal registry
This is done because multi-instance Widgets are directly dependent on repeating Regions. If Regions are unmounted, they become redundant and add to memory leakage.
Nothing extra needs to be done from a developer's point of view, but a new `beforeDestroy` callback is now available:
```js
import { createApp } from 'frint';
const App = createApp({
name: 'MyApp',
initialize: function () {
// called when the App is instantiated
},
beforeDestroy: function () {
// called when App is about to be destroyed
}
});
```
> App lifecycle (destroy)

- site/content/docs/migration/v1.md
* Migration guide updated to import functions from the right packages
* Snippets don't enforce to use aliased functions `createCore` and `createWidget`
* `createApp` is enough, like @alexmiranda suggested
> Migration guide updated to reflect monorepo

- packages/frint/package.json
- packages/frint/src/App.js
* Continuation of https://github.com/Travix-International/travix-di/pull/1
* Now gives @Travix-International members full control over the package that `frint` depends on
> Use forked `travix-di`, instead of `diyai`.

- packages/frint-compat/README.md
- packages/frint-compat/package.json
- packages/frint-model/package.json
- packages/frint-react-server/README.md
- packages/frint-react-server/package.json
- packages/frint-react/README.md
- packages/frint-react/package.json
- packages/frint-store/README.md
- packages/frint-store/package.json
- packages/frint-test-utils/package.json
- packages/frint/README.md
- packages/frint/package.json
- packages/frint/src/index.js
* Drops the concept for plugins via `Frint.use()`
* Because everything is coming from separate npm packages already, not requiring any mutations
> Drop plugin concept

- packages/frint-react/src/components/observe.spec.js
Previously we tested server-side rendering with observed components in PR #128 (it passed).
This PR shows how enzyme can be used for testing observed components too.
@alexmiranda was right about shallow rendering not working. Instead of shallow, I used DOM rendering with enzyme, which has the same API as shallow rendering.
It would be nice to be able to use shallow rendering for testing too, but I don't know why that's not working at this moment.
```js
// shallow - which doesn't work
import { shallow } from 'enzyme';
const wrapper = shallow(<MyObservedComponent />);
expect(wrapper.find('#selector')).to.have.length(1);
// DOM - works for us
import { mount } from 'enzyme';
const wrapper = mount(<MyObservedComponent />);
expect(wrapper.find('#selector')).to.have.length(1);
```
* Shallow …
> Test observed components with enzyme

- packages/frint-compat/src/createApp.spec.js
- packages/frint/README.md
- packages/frint/src/App.js
- packages/frint/src/App.spec.js
* Parent/Child relationship between Apps is now fully hierarchical
* We currently only have `Root App ==> Widget` hierarchy
* With this PR, we now have `Root App ==> As ==> Many ==> Apps ==> Widget`
* More tests written
* Docs provided
* Does not change the behaviour of 1.x in any way, and in fact makes it purer
This PR now makes way for things like: 
* Routing system with nested views
* Concept of Shell App that we discussed before (for PWA), which can closely work with Service Workers
> App hierarchy

- packages/frint-compat/src/extendApp.js
- packages/frint-compat/src/mapToProps.js
* Fix for shared state in old `mapToProps`
> frint-compat: fixes for readableApps.

- site/partials/assets.html
- site/partials/navLinks.html
This is what it looks like, on the home page
On other pages:
Inside the search popup the little underlines are blue, but I couldn't change them with the recommended styles (https://community.algolia.com/docsearch/documentation), so probably we'd have to dig deeper to adjust that.
Please tell if anything should be done differently, and feel free to jump in and change the styles if you'd like to change the looks.
> Add search functionality with Algolia

- packages/frint-preset-travix/README.md
- packages/frint-preset-travix/package.json
* New `frint-preset-travix` package for installing all Frint packages in one go.
* The preset will take care of versioning for all the packages for us.
The primary reason for keeping it in the monorepo is Lerna's feature of automatically updating the version numbers in `package.json` on every new release.
And instead of manually updating all the package's versions in our private repositories later, we only need to update to latest preset every time.
It may be extracted out into a separate repository in future.
> Preset for Travix

- packages/frint-model/README.md
- packages/frint-model/package.json
- packages/frint-model/src/Model.js
- packages/frint-model/src/Model.spec.js
- packages/frint-model/src/createModel.spec.js
Models now support Observables, for streaming changes as they happen. This would be of very high impact for dealing with forms in observed React components.
Import:
```js
import { createModel } from 'frint-model';
```
Create Model class:
```js
const Shirt = createModel({});
```
Building a new model instance:
```js
const shirt = new Shirt({
color: 'blue',
size: 'medium',
});
```
The model instance can also be observed for changes:
```js
shirt.get$().subscribe(function (shirtAttributes) {
// triggered when the model had any change
});
shirt.get$('color').subscribe(function (color) {
// triggered when the model's `color` key changes
});
```
> Make models streamable

- packages/frint-cli/commands/init.js
> frint-cli: fix for `init` by removing extra space from command

- packages/frint-store/src/Store.js
- packages/frint-store/src/combineReducers.spec.js
- packages/frint-store/src/createStore.spec.js
Closes #156 
* There was a bug that required Store's to be always instantiated with `initialState` following the same Object structure for its reducer (especially when it was a combined reducer)
* Initial states in individual reducers were not honoured
* That has been fixed now, with 3 different scenarios well tested
> Fix for initializing Stores with combined reducers

- site/content/docs/migration/v1.md
* Migration guide typos fixed
* Added docs for `PropTypes` migration
* Added note for Component lifecycle methods
> Fix for migration guide typos

- packages/frint-router-react/src/Route.js
- packages/frint-router-react/src/Switch.js
Hopefully, I got the Route propTypes correctly. Please check.
Renamed componentDidMount to componentWillMount, because of this.setState() inside, which would cause new render right after the component did mount.
Decided to keep console.error() just as a reminder that we need to handle errors somehow.
> frint-router-react: fix lint errors

- examples/kitchensink/core/components/Root.js
- examples/kitchensink/core/services/Bar.js
- examples/kitchensink/core/services/Baz.js
- examples/kitchensink/core/services/Foo.js
- packages/frint-compat/src/createApp.spec.js
- packages/frint-compat/src/mapToProps.spec.js
- packages/frint-react-server/src/renderToString.spec.js
- packages/frint-react/src/components/observe.spec.js
- packages/frint/README.md
- packages/frint/src/App.js
- packages/frint/src/App.spec.js
- packages/frint/src/createApp.spec.js
- site/content/docs/migration/v1.md
- site/content/guides/apps.md
- site/content/guides/higher-order-components.md
instead of getOption('name') use the method getName.
issue #184
> frint: new `app.getName` method

- packages/frint-router-react/src/Route.js
- packages/frint-router-react/src/Switch.js
- packages/frint-router-react/src/Switch.spec.js
Some changes in functionality:
- added passing of computedMath to default Route (otherwise it didn't render because there were no match)
- removed React.isValidElement check. I just couldn't come up with unit test for it. if we want to make it fool-proof, we can test it with crazy children like {' '} or () => ... or {15}, so that it would at least issue a warning that it's not a way to go.
> frint-router-react › Switch component: unit tests and a little refactoring

- packages/frint-router/src/matchFromHistory.js
Following Jean's comment: https://github.com/Travix-International/frint/pull/244#discussion_r130294194
> frint-router: check result of RegExp.exec using Array.isArray

- packages/frint-store/README.md
The site shall be redeployed after the PR is merged
> frint-store: Fix wrong combineReducers require in docs

- packages/frint-model/src/createModel.js
Instead of extending the model instance each time, we should extend the Model class definition a single time. This has some benefits:
- Allows us to test model method definitions without instantiating them:
```js
// Before
const myModel = new MyModel(attrs);
expect(myModel.someMethod()).to.equal('something');
// After
expect(MyModel.prototype.someMethod.call(stub)).to.equal('something');
```
- An edge case, but still: It prevents a developer from having model instances with different behaviours (which would happen if the extend object would be modified from outside)
```js
const attrs = {
myMethod() {
return 'something';
}
}
const MyModel = createModel(attrs);
const myModel = new MyModel({});
myModel.myMethod() // -> 'something'
attrs.myMethod = function() {
return 'anotherThing';
}
const …
```
> Extend the prototype of Model at definition time

- .travis.yml
- Makefile
- packages/frint-compat/webpack.config.js
- packages/frint-model/webpack.config.js
- packages/frint-react/webpack.config.js
- packages/frint-router-react/webpack.config.js
We were missing some `externals` in our Webpack configs, which resulted in bigger dist sizes. This has now been fixed.
Those using FrintJS via CDN can now benefit from reduced size.
Added a new `make list-dists` command.
```
$ make list-dists | grep '.min.js'
25K	./packages/frint-compat/dist/frint-compat.min.js
202K	./packages/frint-model/dist/frint-model.min.js
22K	./packages/frint-react/dist/frint-react.min.js
239K	./packages/frint-router-react/dist/frint-router-react.min.js
26K	./packages/frint-router/dist/frint-router.min.js
6.5K	./packages/frint-store/dist/frint-store.min.js
11K	./packages/frint/dist/frint.min.js
```
```
$ make list-dists | grep '.min.js'
15K	./packages/frint-compat/dist/frint-compat.min.js
2.6K	./packages/frint-model/dist/frint-model.min.js
12K …
```
> Apply Webpack’s `externals` more accurately to reduce dist sizes.

- packages/frint-react/src/isObservable.js
While this works great for us for now, this also means anyone else who is importing RxJS like this import { Observable } from 'rxjs/Observable'; would face a problem right away
Closes #274
> Make `isObservable` more generic

- CODE_OF_CONDUCT.md
- README.md
Please @fahad19 let me know if now it is ok :) and thanks for your remarks
> Remove redundant square brackets from Code of Conduct

- packages/frint-react/src/components/Region.js
Declaring the context types in the Region will allow to access the parent app that is being passed by the `observe` hoc.
Fixes #256
> frint-react: Declare app in context of Region

- README.md
Created a new section in the README to mention other community projects.
Currently linking to only https://github.com/frintjs/frint-vue
> Link to `frint-vue`.

- .editorconfig
Closes https://github.com/Travix-International/frint/issues/285
`end_of_line` should not be specified, as it differs from platform to platform. A common approach is to let VCS decide this instead.
A potential future solution for `end_of_line = native` is discussed here:
https://github.com/editorconfig/editorconfig/issues/226
> Remove end of line setting from .editorconfig

- packages/frint-router-react/README.md
- packages/frint-router-react/src/Route.js
- packages/frint-router-react/src/Route.spec.js
Closes #302 
**Note**: No breaking changes.
The `<Route />` component now supports inline rendering via `render` prop:
```js
<Route
path="/about"
render={() => <p>Hi</p>}
/>
```
Doing so would allow passing extra props to the components, without risking any unmounting of the rendered components:
```js
import Foo from './Foo';
const fooProps = {};
<Route
path="/foo"
render={(routeProps) => (
<Foo 
customProps={fooProps} 
{...routeProps} 
/>
)}
/>
```
> frint-router-react: inline rendering via Route component

- .alexrc
- README.md
- packages/frint-model/README.md
- packages/frint-model/src/index.js
- site/partials/docsSidebar.html
Closes #306 
The package will ultimately be removed from this repo once the migration has completed to `frint-data` in our applications.
> frint-model: Deprecated

- examples/counter-ts/core/app/index.ts
- examples/counter/core/app/index.js
- examples/kitchensink/app-color/app/index.js
- examples/kitchensink/app-counter/app/index.js
- examples/kitchensink/app-todos/app/index.js
- packages/frint-store/README.md
- packages/frint-store/src/Store.js
- packages/frint-store/src/createStore.spec.js
- site/content/guides/state-management.md
> frint-store: Deprecate `thunkArgument`, and introduce `deps`

- packages/frint-model/src/createModel.js
- packages/frint-store/src/Store.js
- packages/frint-store/src/createStore.js
Doing so would show warnings right when they are created, instead of waiting for them to be instantiated later (which may or may not happen in an App).
This allows us to catch the warnings early on and more reliably.
> Show  deprecated warnings when creating Store and Model classes

- .gitignore
Officially JetBrains suggests to add only certain files to `.gitignore` file: https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore
There're quite some files it doesn't cover. For example in my case:
```
.idea/codeStyleSettings.xml
.idea/frint.iml
.idea/inspectionProfiles/Project_Default.xml
.idea/misc.xml
.idea/modules.xml
.idea/preferred-vcs.xml
.idea/vcs.xml
```
I think since we're all using different IDEs there's no point of adding any files from .idea folder to the project.
> Update .gitignore to ignore all JetBrains IDEs files under .idea folder

- .gitignore
- Makefile
- packages/frint-compat/webpack.config.js
- packages/frint-component-handlers/webpack.config.js
- packages/frint-component-utils/webpack.config.js
- packages/frint-config/README.md
- packages/frint-config/package.json
- packages/frint-config/src/externals.js
- packages/frint-data/webpack.config.js
- packages/frint-model/webpack.config.js
- packages/frint-react/webpack.config.js
- packages/frint-router-component-handlers/package.json
- packages/frint-router-component-handlers/webpack.config.js
- packages/frint-router-react/webpack.config.js
- packages/frint-router/webpack.config.js
- packages/frint-store/webpack.config.js
- packages/frint/webpack.config.js
- repl/README.md
- repl/index.html
- repl/repl.js
- repl/styles.css
Closes #331 
In webpack configs, `libraryTarget` has been changed to `umd`. 
Only then `externals` for libraries with deep paths (like `rxjs/Observable` instead of just `rxjs`) take effect.
Introduced a local REPL to quickly test locally built dists:
```
$ make repl-serve
```
```
$ make list-dists
original 	 gzipped 	 file
--- 		 --- 		 ---
23.4K 		 4.2K 		 ./packages/frint-data/dist/frint-data.min.js
17.0K 		 3.8K 		 ./packages/frint-react/dist/frint-react.min.js
16.0K 		 3.4K 		 ./packages/frint-router-react/dist/frint-router-react.min.js
26.3K 		 7.9K 		 ./packages/frint-router/dist/frint-router.min.js
9.8K 		 2.9K 		 ./packages/frint-store/dist/frint-store.min.js
12.1K 		 3.1K 		 ./packages/frint/dist/frint.min.js
```
> Webpack: fix for dists

- packages/frint-react/README.md
- packages/frint-react/src/components/observe.js
- packages/frint-react/src/components/observe.spec.js
Closes #338 
`observe` higher-order component can now return props synchronously too, which helps in server-side rendering.
If the beginning of your Component file looks like this:
```js
// components/MyComponent.js
import React from 'react';
import { observe } from 'frint-react';
const MyComponent(props) {
return <p>App name: {props.name}</p>;
}
```
You can do the final `export` in either of the ways:
```js
import { Observable } from 'rxjs';
export default observe(function (app) {
return Observable.of({
name: app.getName(),
});
})(MyComponent);
```
```js
export default observe(function (app) {
return {
name: app.getName(),
};
})(MyComponent);
```
Like mentioned in #338, combining environment variables usage in the server along with Webpack's DefinePlugin in the bundler, the final export …
> frint-react: `observe` HoC can return props synchronously

- packages/frint-react/src/render.js
We were loading the entire `frint-react` library inside the `render` function, when we only needed one specific module there.
We were doing it like this so far for `frint-compat` for supporting v0.x users, which is not needed any more.
`react-dom` is now imported **inside** the `render` function. This has no side-effect, and is mainly done for making way for supporting React Native soon.
React Native doesn't require `react-dom`, and `react-dom` is treated as a peer dependency of `frint-react`.
This means when `frint-react` will be used in a React Native project, where the developer doesn't need to install `react-dom`, it will not throw any error when any module is imported from the package like this:
```js
import { observe } from 'frint-react';
```
Directly importing the module from …
> frint-react: load only required modules for `render`

- README.md
Closes #333 
Listed under community projects in root README.
Read more here: https://github.com/frintjs/frint-react-native
Screenshot of an iOS app built with FrintJS + React Native:
> Add `frint-react-native`

- packages/frint-react/src/components/Region.spec.js
- packages/frint-router-react/src/Link.spec.js
- packages/frint-router-react/src/Route.spec.js
- packages/frint-router-react/src/Switch.spec.js
I've fixed tests by following the [migration guide for enzyme v2 to v3](https://github.com/airbnb/enzyme/blob/master/docs/guides/migration-from-2-to-3.md).
> Fixed frint-router-react tests for React 16 compatibility

- packages/frint-config/src/externals.js
- packages/frint-config/src/index.js
This should resolve the issue with `externals` in examples' `webpack.config.js`.
Once this PR has been merged I will update examples accordingly.
> frint-config: exports

- packages/frint-config/src/externals.js
- packages/frint-config/src/index.js
* Casing of exported keys updated
* All exported `externals` are Arrays (which allows easier concatenation when consumed)
PR labelled as `patch` because `frint-config` is treated as an internal package only, as stated in the root README.
Refs #344
> frint-config: casing for exported keys

- CHANGELOG.md
- LICENSE
- README.md
- examples/counter/package.json
- examples/kitchensink/package.json
- examples/multiple-apps/package.json
- examples/router/package.json
- lerna.json
- package.json
- packages/frint-cli/README.md
- packages/frint-cli/commands/init.js
- packages/frint-cli/package.json
- packages/frint-compat/package.json
- packages/frint-component-handlers/package.json
- packages/frint-component-utils/package.json
- packages/frint-config/package.json
- packages/frint-data/package.json
- packages/frint-model/package.json
- packages/frint-react-server/package.json
- packages/frint-react/package.json
- packages/frint-router-component-handlers/package.json
- packages/frint-router-react/package.json
- packages/frint-router/package.json
- packages/frint-store/package.json
- packages/frint-test-utils/package.json
- packages/frint/package.json
Now that the project has moved to its independent organization, I followed what [Bootstrap](https://github.com/twbs/bootstrap) did when they did something similar:
* License is now accredited to both Authors + Organization ([example](https://github.com/twbs/bootstrap/blob/v4-dev/LICENSE#L4))
* Authors info in manifests point to GitHub's contributors page ([example](https://github.com/twbs/bootstrap/blob/v4-dev/package.json#L15))
Closes #355
> New organization

- .travis.yml
- README.md
- package.json
* Changes our tool to track coverage through history: removes Coveralls, adds Codecov
* Changes the `README.md`: removes Coveralls badge, adds Codecov
However, Codecov is NOT a one-to-one replacement. We were delegating the _coverage check_ to Coveralls. That's not done anymore on Codecov.
For that, there's the need to create a `.nycrc` defining what is our threshold. Will issue a PR next to this one, as it's not directly related. 
- Diffs
Note: While this first PR is not merged, it is not possible to do a _comparison with `master`_ since there's no info - on codecov - about `master`.
> Removes Coveralls in favor of Codecov.

- packages/frint-router-component-handlers/src/createRouteHandler.js
- packages/frint-router-component-handlers/src/createRouteHandler.spec.js
This commit fixes following bug. Whenever `<Route />` instance had `component` prop, and then props change to having `render` prop and not having `component` prop, the `component` would still get rendered (ignoring `render` prop), because if was saved in state and `component` state has priority over `render` prop.
Example code where it was breaking (while switching between routes):
```js
<Switch>
<Route path="/one" component={OneComponent} />
<Route path="/two" render={() => <AnotherComponent />} />
</Switch>
```
Now it's fixed by setting `component` state to `null` whenever `render` prop is present.
> Fix conflict between render and component props in Route component

- packages/frint-router-component-handlers/src/createRouteHandler.spec.js
- packages/frint/src/App.spec.js
- packages/frint/src/createApp.js
When defining and instantiating Apps, the lifecycle methods (`initialize` and `beforeDestroy`) will not be overridden any more.
This means, the methods you pass when creating an App, and also intantiating the App will both trigger.
```js
import { createApp } from 'frint';
const RootApp = createApp({
name: 'RootApp',
initialize() {
console.log('defined when creating App class');
},
});
const app = new RootApp({
initialize() {
console.log('defined when instantiating the App');
}
});
```
The above code will print two logs in this order:
```
defined when creating App class
defined when instantiating the App
```
The API will now allow us to wrap Child Apps' components with ease in a custom bundler level, as mentioned in #376.
We can now do something like:
```js
window.app.registerApp(ChildApp, …
```
> frint: handle App lifecycle events without overriding options

- packages/frint/src/App.spec.js
- packages/frint/src/createApp.js
When `initialize` is defined both at the time of creation and instantiation of the apps, they didn't have proper `this` context so it couldn't for example access providers with `this.get(...)`. This PR fixes the issue.
> Ensure proper `this` context in lifecycle callbacks

- README.md
The characteristics were initially listed in #386.
> Readme: updated with features list

- packages/frint-component-utils/src/streamProps.js
- packages/frint-component-utils/src/streamProps.spec.js
- packages/frint-react-server/src/renderToString.spec.js
- packages/frint-react/src/components/observe.js
- packages/frint-react/src/components/observe.spec.js
Closes #390 
When an Observable is returned from the `observe` higher-order component, it will now check if it has a static `defaultProps` property, and set that as default props to start with.
The `streamProps` helper function will now ultimately generate an Observable with `defaultProps` static property, if it received any via `streamProps(defaultProps)`.
As of our last release, you need to take care of the props based on what environment you are in:
```js
import { observe, streamProps } from 'frint-react';
function MyComponent(props) {
return '';
}
export default observe(function () {
const defaultProps = { foo: 'foo value here' };
if (process.env.BABEL_ENV === 'server') {
// handle it synchronously
return defaultProps;
}
// Observable
return streamProps(defaultProps)
.set(...) …
```
> frint-react: start props stream with default props synchronously

- packages/frint-data/README.md
- packages/frint-data/src/Types.js
- packages/frint-data/src/Types.spec.js
- packages/frint-data/src/createModel.js
- packages/frint-data/src/createModel.spec.js
Added a new `Types.date` in the API.
```js
import { createModel, Types } from 'frint-data';
const Todo = createModel({
schema: {
createdAt: Types.date,
},
});
```
Can be instantiated with either Date objects, or a string that `Date.parse()` can understand:
```js
const todo1 = new Todo({
createdAt: new Date(),
});
const todo2 = new Todo({
createdAt: 'Thu Dec 28 2017 08:04:56 GMT+0000 (UTC)',
});
```
When using `model.toJS()`, it will return the value as a string according to `date.toISOString()`:
```js
const createdAt = someTodo.toJS().createdAt; // `2017-12-28T16:29:26.258Z`
```
> frint-data: support Date as a type

- packages/frint/index.d.ts
I started experimenting with migrating one of the packages to TypeScript, and discovered some incorrect signatures in the `d.ts` typings (there might be more) in the `getApps$` function:
- the `regionName` argument should be optional
- the `Observable` in the result is returning an array, not just a single app
Without the fix we get the following errors:
and
> Fix the signature of the function getApps$ in the d.ts

- packages/frint/src/App.js
- packages/frint/src/App.spec.js
From providers, it was not possible to listen to Child App registrations before, because the dependencies were resolved BEFORE defining the Subject for apps list.
The Subject has been moved above now, without causing any unintended side-effects.
```js
const Root = createApp({
name: 'RootApp',
providers: [
{
name: '__EXEC__',
useFactory({ app }) {
// before, it was not possible to call `app.getApps$()` here
app.getApps$().subscribe(x => console.log(x);
},
deps: ['app'],
},
],
});
```
> frint: Support listening to Child App registrations from providers

- packages/frint-react/src/components/observe.js
- packages/frint-react/src/components/observe.spec.js
Add `name` as a fallback for `displayName` when defining the display name of an observed component.
Usually, we don't need to set `displayName` explicitly because it's inferred from the name of the function or class that defines the component. However, this inferred value may be set as a `name` class property instead, so we should consider this case as well.
This change follows the convention for [wrapping the display name of a wrapped component](https://reactjs.org/docs/higher-order-components.html#convention-wrap-the-display-name-for-easy-debugging) from React docs.
> frint-react: improve display name of observed components

- packages/frint-cli/src/bin/frint.ts
- packages/frint-cli/src/commands/help.spec.ts
- packages/frint-cli/src/commands/version.spec.ts
- packages/frint-di/index.d.ts
- packages/frint/src/App.ts
In practice `Container.get()` returns instance of a provider, which can be anything.
`Provider` interface is a definition of provider, not instance. Therefore typing was incorrect.
Make `options` optional in createContainer() definition
> frint-di: Fix Container.get() return type

- packages/frint-cli/src/bin/frint.ts
- packages/frint-cli/src/commands/help.spec.ts
- packages/frint-cli/src/commands/version.spec.ts
- packages/frint-cli/src/providers.mock.ts
- packages/frint-cli/src/providers.ts
- packages/frint-di/index.d.ts
- packages/frint/src/App.spec.ts
- packages/frint/src/App.ts
Following suggestion by @markvincze, I've changed Container.get() signature from `get(name: string): any;` to `get<T>(name: string): T;`.
This not only allows to leverage type safety of TypeScript, but requires to use it.
Previously Container type was optional
```ts
const console: Console = container.get('console');
console.log()
```
Now if you don't specify `<Console>` it'll default to `{}` (empty object type) and `console.log()` won't compile. This is not ideal but unfortunately I don't know the way to require generic type in TS.  Nevertheless it achieves the goal of making type required, because without using the type you pretty much cannot use the value received from the container.
```ts
const console = container.get<Console>('console');
console.log() // works
```
```ts
const console …
```
> Define type of Container.get() return value with generic

- packages/frint/src/App.ts
- packages/frint/src/index.ts
The three errors were encountered when moving the exemplar Multiple-Apps project to Typescript.
In file: `core/app/index.ts`
```Typescript
import { createApp, AppClass } from 'frint';
import RootComponent from '../components/Root';
export default createApp({
name: 'MiskApp',
providers: [
{
name: 'component',
useValue: RootComponent,
},
],
});
```
Error 1
---
Within VS Code, the following Typescript error was raised
```
Default export of the module has or is using private name 'AppClass'.
```
And at compile time, this error is raised.
```
ERROR in [at-loader] ./src/core/app/index.ts:1:21
TS2305: Module '"/Users/aparadi/Development/misk-admin/main/node_modules/frint/lib/index"' has no exported member 'AppClass'.
```
Based on the first part of this error, the issue is found to be that …
> [#406][#412] Fix 3 frintTypescript Errors

- packages/frint-react/README.md
- packages/frint-react/src/hydrate.js
- packages/frint-react/src/hydrate.spec.js
- packages/frint-react/src/index.js
- packages/frint-react/src/index.spec.js
Add `hydrate` function to `frint-react`.
Support hydration from server-rendered HTML.
Closes #335.
> frint-react: add `hydrate` function to `frint-react`

- packages/frint/README.md
- packages/frint/src/App.spec.ts
- packages/frint/src/App.ts
- Add optional `methods` (`Object`) property to `AppOptions`, which has its properties added to the app's `this` object.
- Add `app.getMethods` method which returns the app's `methods` object.
Allow access to public methods directly from the app instance, besides the `options` property.
Closes #426.
> frint: Expose class methods on the app instance level

- packages/frint-react/src/components/Region.js
Fix typo in `Region`'s `children` prop type.
When render props were implemented, the `Region`'s `children` prop type was mistakenly assigned to `PropTypes.function` instead of `PropTypes.func`, which causes the following warning:
> Warning: Failed prop type: Region: prop type `children` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`.
> frint-react: Fix typo in `children` prop type

- packages/frint-component-handlers/src/RegionHandler.js
- packages/frint-react/README.md
- packages/frint-react/src/components/Region.js
- packages/frint-react/src/components/Region.spec.js
Forward all Region props but `children` and `className` to the App's component by default.
Make it easier to access Region props from an App's component, without having to setup observers and forward the props yourself.
> frint-react:  Forward `Region` props to children components

- packages/frint/src/App.ts
Extend Method Interface to receive arguments in methods.
Ex: 
```typescript
const exampleApp = createApp({
name: 'Example',
methods: {
sum: (a: number, b: number): number =>  a + b
}
});
```
> Fixes #437 - Add generic type for Frint Methods interface

- packages/frint-react/index.d.ts
In order to have more accurate type checking, we are changing the return of `getMountableComponent` to`React.SFC`.
```javascript
// getMountableComponent.js:17 returning a React.StatelessComponent
return (props) => {
return <ComponentInProvider {...props} />;
};
```
> Fix getMountableComponent type changing to React.SFC
